version: "3.9"

services:
    database:
        image: postgres
        container_name: database_queries
        restart: always
        ports: 
            - 5432:5432
            - 9229:9229 
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=queries_challenge
        volumes:
            - pgdata:/data/postgres


    app:
        build: .
        container_name: queries_challeng
        ports:
            - 3333:3333
        volumes: 
            - .:/usr/app
        links: 
            - database
        depends_on:
            - database

volumes: 
    pgdata:
        driver: local
